"""empty message

Revision ID: 048e1f613f18
Revises: 3fbd27e7ae43
Create Date: 2026-05-26 01:21:16.555741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '048e1f613f18'
down_revision = '3fbd27e7ae43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spoken_language', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_column('spoken_language')

    # ### end Alembic commands ###
