"""empty message

Revision ID: 10beb5149e0a
Revises: 048e1f613f18
Create Date: 2026-05-26 10:31:59.335690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10beb5149e0a'
down_revision = '048e1f613f18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
