"""empty message

Revision ID: 1514dd3215cb
Revises: a9549f3fa077
Create Date: 2026-05-26 13:23:25.620553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1514dd3215cb'
down_revision = 'a9549f3fa077'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
