"""empty message

Revision ID: 1d886a355ac5
Revises: 10beb5149e0a
Create Date: 2026-05-26 10:41:14.510994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d886a355ac5'
down_revision = '10beb5149e0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
