"""empty message

Revision ID: 2999d65630ad
Revises: c137716da6ef
Create Date: 2026-05-26 14:20:31.101155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2999d65630ad'
down_revision = 'c137716da6ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
