"""empty message

Revision ID: 37ca8ecfc4c9
Revises: 8eb7e26d21b5
Create Date: 2026-05-26 12:54:21.482161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37ca8ecfc4c9'
down_revision = '8eb7e26d21b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
