"""empty message

Revision ID: 3fbd27e7ae43
Revises: 3b9a1dd373f7
Create Date: 2026-05-25 01:33:30.354398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fbd27e7ae43'
down_revision = '3b9a1dd373f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class_summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('study_group_note', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_column('study_group_note')
        batch_op.drop_column('class_summary')

    # ### end Alembic commands ###
