"""empty message

Revision ID: 64060d8c0c1e
Revises: 6cf67b844d0d
Create Date: 2026-05-26 12:51:32.046145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64060d8c0c1e'
down_revision = '6cf67b844d0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
