"""empty message

Revision ID: 64d3af4f4dcc
Revises: ccc2f58645b4
Create Date: 2026-05-26 12:53:03.221318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64d3af4f4dcc'
down_revision = 'ccc2f58645b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
