"""empty message

Revision ID: 6cf67b844d0d
Revises: 1d886a355ac5
Create Date: 2026-05-26 12:46:04.147162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cf67b844d0d'
down_revision = '1d886a355ac5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
