"""rename course fields to english

Revision ID: 7d6124f6b404
Revises: a05fdb151e72
Create Date: 2026-04-10 09:44:10.043462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
"""rename course fields to english

Revision ID: 7d6124f6b404
Revises: a05fdb151e72
Create Date: 2026-04-10 09:44:10.043462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d6124f6b404'
down_revision = 'a05fdb151e72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('profesor', new_column_name='professor')
        batch_op.alter_column('horario', new_column_name='schedule')
        batch_op.alter_column('ubicacion', new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('professor', new_column_name='profesor')
        batch_op.alter_column('schedule', new_column_name='horario')
        batch_op.alter_column('location', new_column_name='ubicacion')

    # ### end Alembic commands ###
