"""empty message

Revision ID: 8eb7e26d21b5
Revises: dd1ece7fb70f
Create Date: 2026-05-26 12:54:13.753890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8eb7e26d21b5'
down_revision = 'dd1ece7fb70f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
