"""empty message

Revision ID: 9087f1448a22
Revises: 64060d8c0c1e
Create Date: 2026-05-26 12:51:32.374305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9087f1448a22'
down_revision = '64060d8c0c1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
