"""empty message

Revision ID: 97ee744d09f5
Revises: 37ca8ecfc4c9
Create Date: 2026-05-26 12:54:21.747915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97ee744d09f5'
down_revision = '37ca8ecfc4c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
