"""change course fields

Revision ID: a05fdb151e72
Revises: f9c6aa5fc95a
Create Date: 2026-04-10 09:39:53.362047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a05fdb151e72'
down_revision = 'f9c6aa5fc95a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profesor', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('horario', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('ubicacion', sa.String(length=128), nullable=True))
        batch_op.drop_column('category')
        batch_op.drop_column('semester')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('semester', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=32), nullable=True))
        batch_op.drop_column('ubicacion')
        batch_op.drop_column('horario')
        batch_op.drop_column('profesor')

    # ### end Alembic commands ###
