"""empty message

Revision ID: a9549f3fa077
Revises: 97ee744d09f5
Create Date: 2026-05-26 13:11:37.760178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9549f3fa077'
down_revision = '97ee744d09f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
