"""empty message

Revision ID: c137716da6ef
Revises: e825fd16c57b
Create Date: 2026-05-26 13:23:51.177532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c137716da6ef'
down_revision = 'e825fd16c57b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
