"""empty message

Revision ID: ccc2f58645b4
Revises: 7b7445668807
Create Date: 2026-05-26 12:52:50.083879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccc2f58645b4'
down_revision = '7b7445668807'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
