"""empty message

Revision ID: dd1ece7fb70f
Revises: 64d3af4f4dcc
Create Date: 2026-05-26 12:53:03.486289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd1ece7fb70f'
down_revision = '64d3af4f4dcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
