"""empty message

Revision ID: e825fd16c57b
Revises: 1514dd3215cb
Create Date: 2026-05-26 13:23:50.967178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e825fd16c57b'
down_revision = '1514dd3215cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
