"""empty message

Revision ID: f5c5a1600074
Revises: 2999d65630ad
Create Date: 2026-05-26 14:20:36.354736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5c5a1600074'
down_revision = '2999d65630ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
